### ISSUE TITLE
Bug?: Disabling auto-treecutting also stops sowing when not using new map

### ISSUE THREAD

**Issue by shentino** [ArcticOwl-Dev/DoNotAutoCutTrees#3]
For some reason I've reliably been able to notice that disabling auto treecutting also disables being able to sow.

Paradoxically, I've observed this behavior can only seem to be reproduced on a map where I added the mod after starting a map.

I can't reproduce it on a fresh map that was started while the mod was enabled.

Could it be an issue with enabling the mod on a save that had it disabled?

**Comment by shentino** [comment]
Wrong file, here's the right one.  Sorry, I got slopp
[Treaty of Thatederia (Permadeath).rws.gz](https://github.com/AllenCaine/DoNotAutoCutTrees/files/7445440/Treaty.of.Thatederia.Permadeath.rws.gz)
y

**Comment by shentino** [comment]
Actually I just discovered something very interesting!

It seems trees have a general exclusion zone for cutting for a 3x3 area around them.

Sorta seems to go along with grow zones normally chopping trees within 1 tile of the border.

This also explains every other mod I've tried such as "no grow zone logging" as well as "cut everything in zone"'s tree-exemption option.

My guess is this is some sort of quirk of the base game

**Comment by AllenCaine** [comment]
When i load your safegame, only with Harmony and DoNotAutoCutTrees Mod your pawns sowing new plants, when i expand your growing zone. Your current growing zones only exist of trees 😆 
<img src="https://user-images.githubusercontent.com/56565659/139577421-d9731f4c-d0db-4ba6-9160-4f4aa7384740.png" width="50%" height="50%">

------------
> It seems trees have a general exclusion zone for cutting for a 3x3 area around them.

Yeah that is what i meant with my comment 2 days ago ^^

> (Trees prevent sowing on there cell and also all eight sorrounding cells.)
https://github.com/AllenCaine/DoNotAutoCutTrees/issues/3#issuecomment-954425323

-------

> My guess is this is some sort of quirk of the base game

What do you mean with that?
